import os
from pathlib import Path

# load .env file if it exists (copy .env.example -> .env and fill in your key)
try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).resolve().parent / ".env")
except ImportError:
    pass  # python-dotenv not installed, fall back to system env vars


# paths
PROJECT_ROOT = Path(__file__).resolve().parent
DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
MERGED_DIR = DATA_DIR / "merged"
AUGMENTED_DIR = DATA_DIR / "augmented"
RUNS_DIR = PROJECT_ROOT / "runs"

# YOLO dataset config file (auto-generated by collect_data.py)
DATA_YAML = DATA_DIR / "data.yaml"

# target classes (unified across all datasets)
TARGET_CLASSES = [
    "cow",
    "buffalo",
    "goat",
    "dog",
    "wild_boar",
    "monkey",
    "nilgai",
    "elephant",
    "deer",
    "bird",
]
NUM_CLASSES = len(TARGET_CLASSES)

# Mapping from various dataset label names → our unified class names.
# Add more aliases as you encounter them in new datasets.
LABEL_ALIASES = {
    # Cow variants
    "cow":          "cow",
    "cattle":       "cow",
    "indian_cow":   "cow",
    "cows":         "cow",
    "Cow":          "cow",
    "Cattle":       "cow",
    "bull":         "cow",
    "Bull":         "cow",
    "ox":           "cow",
    "Ox":           "cow",
    "calf":         "cow",
    "Calf":         "cow",
    # Indian cow breed names (from indian-cows & indian-bovine datasets — all map to "cow")
    "Gir":              "cow",
    "gir":              "cow",
    "Deoni":            "cow",
    "deoni":            "cow",
    "Banni":            "cow",
    "banni":            "cow",
    "Bargur":           "cow",
    "bargur":           "cow",
    "Alambadi":         "cow",
    "alambadi":         "cow",
    "Amritmahal":       "cow",
    "amritmahal":       "cow",
    "Ayrshire":         "cow",
    "ayrshire":         "cow",
    "Dangi":            "cow",
    "dangi":            "cow",
    "Sahiwal":          "cow",
    "sahiwal":          "cow",
    "Tharparkar":       "cow",
    "tharparkar":       "cow",
    "Kankrej":          "cow",
    "kankrej":          "cow",
    "Ongole":           "cow",
    "ongole":           "cow",
    "Red Sindhi":       "cow",
    "red_sindhi":       "cow",
    "Hariana":          "cow",
    "hariana":          "cow",
    "Rathi":            "cow",
    "rathi":            "cow",

    # Buffalo variants
    "buffalo":          "buffalo",
    "Buffalo":          "buffalo",
    "water_buffalo":    "buffalo",
    "Water Buffalo":    "buffalo",
    "indian_buffalo":   "buffalo",
    "buffaloes":        "buffalo",
    # Indian buffalo breed names (from murrah-buffalo & buffalo-detection datasets)
    "Murrah":           "buffalo",
    "murrah":           "buffalo",
    "murrah_buffalo":   "buffalo",
    "Murrah Buffalo":   "buffalo",

    # Goat variants
    "goat":     "goat",
    "Goat":     "goat",
    "goats":    "goat",
    "Goats":    "goat",
    # Sheep mapped to goat — the sheep_goat Roboflow dataset uses "sheep" as a label.
    # Sheep and goat are visually similar enough to treat as one class for detection.
    "sheep":    "goat",
    "Sheep":    "goat",
    "sheep-goat": "goat",

    # Dog variants
    "dog":          "dog",
    "Dog":          "dog",
    "dogs":         "dog",
    "stray_dog":    "dog",
    "Stray Dog":    "dog",
    "stray-dog":    "dog",

    "wild_boar":    "wild_boar",
    "Wild Boar":    "wild_boar",
    "wild-boar":    "wild_boar",
    "wild boar":    "wild_boar",
    "Wild boar":    "wild_boar",
    "boar":         "wild_boar",
    "Boar":         "wild_boar",
    "pig":          "wild_boar",
    "Pig":          "wild_boar",
    "piglet":       "wild_boar",
    "wild_pig":     "wild_boar",
    "Wild Pig":     "wild_boar",
    "sus_scrofa":   "wild_boar",

    "monkey":           "monkey",
    "Monkey":           "monkey",
    "monkeys":          "monkey",
    "Monkeys":          "monkey",
    "monkey-1":         "monkey",
    "macaque":          "monkey",
    "Macaque":          "monkey",
    "rhesus_macaque":   "monkey",
    "Rhesus Macaque":   "monkey",
    "langur":           "monkey",
    "Langur":           "monkey",
    "primate":          "monkey",
    "Primate":          "monkey",

    # Nilgai variants
    "nilgai":           "nilgai",
    "Nilgai":           "nilgai",
    "nilgai_antelope":  "nilgai",
    "Nilgai Antelope":  "nilgai",
    "blue_bull":        "nilgai",
    "Blue Bull":        "nilgai",
    "blue bull":        "nilgai",
    "Blue bull":        "nilgai",
    "bluebull":         "nilgai",
    "neel_gai":         "nilgai",
    "NILGAI":           "nilgai",
    "antilope":         "nilgai",
    "ANTILOPE":         "nilgai",

    # Elephant variants
    "elephant":          "elephant",
    "Elephant":          "elephant",
    "elephants":         "elephant",
    "Elephants":         "elephant",
    "aggressive-elephant":"elephant",
    "aggressive_elephant":"elephant",
    "Aggressive Elephant":"elephant",
    "loxodonta":         "elephant",
    "0":                 "elephant",  # Single-class elephant dataset mapping

    # Deer variants
    "deer":             "deer",
    "Deer":             "deer",
    "deers":            "deer",
    "Deers":            "deer",
    "buck":             "deer",
    "Buck":             "deer",
    "doe":              "deer",
    "Doe":              "deer",
    "fawn":             "deer",
    "Fawn":             "deer",
    "whitetail_deer":   "deer",
    "Whitetail Deer":   "deer",
    "whitetail":        "deer",
    "axis_axis":        "deer",
    "chital":           "deer",
    "Chital":           "deer",
    "spotted deer":     "deer",
    "Spotted Deer":     "deer",
    "spotted_deer":     "deer",
    "SikaDeer":         "deer",
    "sika_deer":        "deer",
    "RoeDeer":          "deer",
    "roe_deer":         "deer",
    "sambar":           "deer",
    "Sambar":           "deer",
    # NOTE: "mature", "mid", "young" were removed — too generic, risk mislabeling other animals.
    "doe-body":         "deer",
    "fawn-body":        "deer",
    "mature-body":      "deer",  # Kept with -body suffix (specific enough)
    "young-body":       "deer",  # Kept with -body suffix (specific enough)

    # Bird variants
    "bird":             "bird",
    "Bird":             "bird",
    "birds":            "bird",
    "Birds":            "bird",
    "crow":             "bird",
    "Crow":             "bird",
    "crows":            "bird",
    "Crows":            "bird",
    "peacock":          "bird",
    "Peacock":          "bird",
    "peacocks":         "bird",
    "Peacocks":         "bird",
    "peahen":           "bird",
    "Peahen":           "bird",
    "parrot":           "bird",
    "Parrot":           "bird",
    "parrots":          "bird",
    "Parrots":          "bird",
    "budgerigar":       "bird",
    "myna":             "bird",
    "Myna":             "bird",
    "pigeon":           "bird",
    "Pigeon":           "bird",
    "sparrow":          "bird",
    "Sparrow":          "bird",
    "Indian-Peacock":   "bird",
    "Indian Peacock":   "bird",
    "Indian_Peacock":   "bird",
    "Owl":              "bird",
    "owl":              "bird",
    "Kingfisher":       "bird",
    "kingfisher":       "bird",

    # Dog variants (additional)
    "wild dog":         "dog",
    "Wild Dog":         "dog",
    "wild_dog":         "dog",
}

# Roboflow configuration
# Set your API key as an environment variable before running collect_data.py:
#   Windows:  set ROBOFLOW_API_KEY=your_key_here
#   Linux/Mac: export ROBOFLOW_API_KEY=your_key_here
# Get your key from: https://app.roboflow.com → Settings → API Keys
ROBOFLOW_API_KEY = os.environ.get("ROBOFLOW_API_KEY", "")

# Curated list of Roboflow Universe datasets to download.
# Format: (workspace, project, version, description)
# Only datasets with CC BY 4.0 or more permissive licenses are included.
ROBOFLOW_DATASETS = [
    # ── Nilgai detection ──
    ("visiontest-kcaqk", "nilgai-zsiad-s9fov", 1,
     "Nilgai object detection dataset"),

    # ── Cattle / buffalo species ──
    ("cattle-buexm", "cattlespecies", 1,
     "Cattle and buffalo species detection dataset"),
    ("cattle-buexm", "buffalo-cow", 1,
     "Buffalo and cow detection dataset"),
    ("wrkusuma", "cow-detection-owqvd", 1,
     "High-density cow object detection dataset"),
    ("team-synora", "cattle-buffalo-other", 1,
     "Large-scale cattle and buffalo dataset"),

    # ── PHASE 5: Dedicated Buffalo datasets (browser-verified) ──
    ("ptr-hergu", "buffalo-detection-ehb4t", 1,
     "Buffalo detection — 614 images, dedicated buffalo-only dataset (verified)"),
    ("arjun-t7gxt", "murrah-buffalo-m3trl-0gbss", 1,
     "Murrah buffalo — 104 images, India's most common buffalo breed (verified)"),

    # ── PHASE 6 NEW: Additional buffalo datasets to fix chronic Buffalo misclassification ──
    # These provide structural diversity (different breeds, angles, field contexts)
    # that colour-based confusion cannot solve — especially critical for IR/night mode.
    ("cattle-buexm", "water-buffalo", 1,
     "Water buffalo — dedicated water buffalo dataset (phase 6 new)"),
    ("livestock-0rbki", "buffalo-detection-qjcqe", 1,
     "Buffalo detection — diverse outdoor buffalo images (phase 6 new)"),
    ("aakritikhare", "buffalo-detection-dlpcc", 1,
     "Buffalo detection — close-up and herd buffalo images (phase 6 new)"),
    ("swapnilbhadane", "buffalo-detection-zyjac", 1,
     "Buffalo — farm and rural buffalo images (phase 6 new)"),

    # ── PHASE 5: Indian Cow datasets (browser-verified) ──
    ("aceofstades", "indian-cows-jkbqs", 1,
     "Indian cows — 1,668 images, Gir/Deoni/Banni breeds, diverse outdoor (verified)"),
    ("pib-e46kr", "indian-bovine", 3,
     "Indian bovine — 482 images, 36 Indian breeds annotated (verified)"),

    # ── PHASE 6 NEW: More cow datasets to improve Cow recall and separate from Buffalo ──
    ("pib-e46kr", "indian-bovine", 4,
     "Indian bovine v4 — updated version with additional Indian breed images (phase 6 new)"),
    ("livestock-0rbki", "cow-detection-qqgjq", 1,
     "Cow detection — outdoor farm cows, diverse Indian breeds (phase 6 new)"),

    # ── Wild boar detection ──
    ("trackabox-4ejy9", "wild-boar-a1flm", 1,
     "Wild boar object detection dataset"),

    # ── Crop-damaging Birds dataset ──
    ("puspendu-ai-vision-workspace", "birds-detection-uem1j", 1,
     "Indian bird detection dataset (crow, peacock, parrot)"),

    # ── VERIFIED Asian & General Elephant Datasets ──
    ("customdataset-aucsj", "asian-elephants-dataset", 1,
     "Asian Elephant dataset (verified)"),
    ("ai-xkb2k", "elephant-detection-jzl9g", 1,
     "Elephant detection — diverse camera trap & forest angles (verified)"),
    ("new-cgdeg", "elephants-detection-using-yolo-vlyrb", 1,
     "Elephants detection YOLO (verified)"),

    # ── VERIFIED Indian Goat Datasets ──
    ("goatdataset", "goat-swaod", 4,
     "Goat detection — verified real goat photos (167 images)"),
    ("kushal-xv5o9", "goat-detection-bpjfj", 1,
     "Goat detection — outdoor/natural context (1145 images)"),

    # ── VERIFIED Deer Datasets ──
    ("kuba-kulik-4wi43", "deer-hcuvr", 1,
     "Deer detection — verified outdoor deer photos (1200 images)"),
    ("new-workspace-onq0e", "deer-8swm3", 2,
     "Deer detection — large diverse deer dataset (3213 images)"),

    # ── VERIFIED Stray Dog Datasets ──
    ("fyp-gztsq", "stray-dogs-2wfjc", 1,
     "Stray dog detection (verified)"),
    ("poopdet", "dog-zcf9s", 1,
     "Dog detection — diverse real outdoor dog photos (472 images)"),
    # ── PHASE 5 NEW: Large Dog datasets (browser-verified) ──
    ("imaging-system-avmbz", "stray-dog-control", 1,
     "Stray dog control — 5,500 images, outdoor/street stray dogs (verified)"),
    ("edlin", "dog-detection-jbacv", 1,
     "Dog detection — 3,800 images, diverse stray dog photos (verified)"),

    # ── VERIFIED Clean Monkey Datasets ──
    ("nishad-wttrd", "monkey-detection-w0pyk", 1,
     "Monkey detection outdoor (verified)"),
    ("monketdataset", "monkey-detection-9zwei", 1,
     "Monkey dataset outdoor (verified)"),
    ("plothole", "monkey-detection-07g3w", 1,
     "Plothole monkey detection outdoor (verified)"),
    # ── PHASE 5 NEW: Additional Monkey datasets (browser-verified) ──
    ("gourab-biswas-xoa8r", "monkey-ii5mq", 1,
     "Monkey detection — 232 images, diverse outdoor monkey (verified)"),
    ("monkey-detection-hoaw1", "monkey-detection-xkvfj", 2,
     "Monkey detection — 556 images, diverse monkey dataset (verified)"),
]

# 3.5. CLASS BALANCING SETTINGS (Training Split Only)
# Caps majority classes to prevent dominating training (undersampling)
CLASS_MAX_ANNOTATIONS = {
    # PHASE 6: Caps for Cow and Buffalo raised significantly to absorb all new data.
    # These are the ONLY two weak classes from the 350-epoch YOLO11m baseline.
    # All other classes are already ≥88% mAP@0.5 — their caps are kept.
    "cow":       6000,   # RAISED from 3500 → absorb phase 6 additional cow datasets
    "buffalo":   6000,   # RAISED from 3500 → absorb 4 new buffalo datasets (chronic weakest class)
    "goat":      2500,
    "dog":       4500,
    "wild_boar": 2500,
    "monkey":    4000,
    "nilgai":    3000,
    "elephant":  3500,   # Elephant is 92.4% in baseline — keep cap, no new data needed
    "deer":      3000,
    "bird":      2500,
}

# Duplicates minority classes to boost representation (oversampling multiplier)
# NOTE: Only use this for REAL augmentation via augment_weak_classes.py
# DO NOT set this to > 1.0 (exact duplicates add no new information).
CLASS_OVERSAMPLE_MULTIPLIER = {
    # Dog augmentation is handled by augment_weak_classes.py which creates
    # genuinely different images (crop/zoom/flip/brightness variants)
    # rather than exact copies. Leave this empty.
}

# augmentation settings
# Fraction of training images to convert into synthetic IR
# PHASE 6: Reduced from 0.40 → 0.20
# At 0.40, IR creates 24,800 new images (mild+harsh × 40%) = +2.5GB BEFORE weak-class augment.
# With buffalo 8x (76,992 images) and only 9-10GB free, the disk fills up and crashes.
# 0.20 still gives 12,400 synthetic night images — enough for robust night detection.
IR_AUGMENT_RATIO = 0.20  # 20% of training images

# Synthetic IR pipeline parameters
IR_SETTINGS = {
    "mild": {
        "gamma_range": (0.6, 0.9),         # Slight darkening
        "gauss_noise_std": (0.01, 0.03),    # Light sensor noise (std_range)
        "iso_noise_intensity": (0.05, 0.15),
        "clahe_clip_limit": 3.0,
        "blur_limit": 3,
        "brightness_limit": (-0.15, 0.05),
        "contrast_limit": (0.1, 0.3),
        "vignette_p": 0.3,
    },
    "harsh": {
        "gamma_range": (0.3, 0.6),          # Strong darkening
        "gauss_noise_std": (0.03, 0.08),    # Heavy sensor noise (std_range)
        "iso_noise_intensity": (0.15, 0.4),
        "clahe_clip_limit": 5.0,
        "blur_limit": 5,
        "brightness_limit": (-0.3, -0.05),
        "contrast_limit": (0.2, 0.5),
        "vignette_p": 0.6,
    },
}

# training hyperparameters

# How many epochs are already baked into last.pt (the checkpoint you upload to Kaggle).
# YOLO sets epoch=-1 in a cleanly-finished checkpoint, making it unreadable from the file.
# Update this number each time you start a new Kaggle session from a new checkpoint.
# PHASE 6: Starting from the YOLO11m 350-epoch best.pt (runs-10class-350/animal_guard_train/weights/best.pt).
# This is the definitive baseline — YOLO11m at 86.3% mAP@0.5. Phase 5 YOLO11n branch is discarded.
CHECKPOINT_EPOCH = 350

TRAIN_CONFIG = {
    # model
    # PHASE 6: YOLO11m (Medium) — same architecture as the 350-epoch baseline.
    # Phase 5 YOLO11n was a mistake: smaller model lost Elephant (92.4%→69.4%).
    # We resume from runs-10class-350/animal_guard_train/weights/best.pt.
    "model": "yolo11m.pt",

    # schedule
    "epochs": 450,              # Target: 450 total cumulative epochs (100 more from checkpoint 350).
    "patience": 40,
    "cos_lr": True,
    "close_mosaic": 15,

    # resolution / batching
    "imgsz": 512,
    "batch": 24,
    "multi_scale": False,

    # hardware
    "device": 0,
    "amp": True,
    "workers": 2,

    # optimizer / loss
    "optimizer": "SGD",
    "lr0": 0.0005,              # Fine-tuning LR (same as Phase 3+4).
    "lrf": 0.02,                # Final LR = 0.0005 × 0.02 = 0.00001
    "momentum": 0.937,
    "weight_decay": 0.0005,
    # PHASE 6 KEY CHANGE: cls raised from 0.7 → 1.0
    # Cow↔Buffalo confusion is a CLASSIFICATION error, not a detection error.
    # Higher cls loss forces the model to invest more gradient into getting the
    # class right, rather than tolerating misclassification on look-alike animals.
    "cls": 1.0,

    # augmentation
    "mosaic": 1.0,
    # PHASE 6 KEY CHANGE: mixup lowered from 0.35 → 0.10
    # At 0.35, MixUp frequently blends cow images with buffalo images, creating
    # ambiguous training signals (the model sees a half-cow/half-buffalo blend).
    # Lowering to 0.10 nearly eliminates this source of class confusion.
    "mixup": 0.10,
    "copy_paste": 0.25,
    "degrees": 15.0,
    "translate": 0.2,
    "scale": 0.9,
    "shear": 2.0,
    "flipud": 0.0,
    "fliplr": 0.5,
    "hsv_h": 0.015,
    "hsv_s": 0.7,
    "hsv_v": 0.4,

    # output
    "project": str(RUNS_DIR),
    "name": "animal_guard_train",
    "exist_ok": True,
    "save": True,
    "save_period": 5,
    # cache="disk" caches preprocessed images to disk (not RAM).
    # RAM cache (cache=True) OOMs Kaggle's 16GB environment with 50k+ images.
    "cache": "disk",
}

# inference settings

# --- Motion detection (MOG2) parameters ---
MOTION_CONFIG = {
    "history": 500,             # Number of frames for background model
    "var_threshold": 50,        # Variance threshold for foreground
    "detect_shadows": False,    # Disable shadow detection for speed
    "learning_rate": 0.005,     # Background update rate

    # Morphological filtering
    "erode_kernel": 3,          # Erosion kernel size
    "dilate_kernel": 7,         # Dilation kernel size
    "morph_iterations": 2,      # Number of morph iterations

    # Contour filtering
    "min_contour_area": 800,    # Minimum pixel area to consider as motion
    "bbox_padding": 0.20,       # 20% padding around motion bounding box

    # Warmup
    "warmup_frames": 30,        # Frames to skip while MOG2 builds background
}

# --- SAHI (Sliced Aided Hyper Inference) parameters ---
# IMPORTANT: slice size must match training imgsz (512px) — NOT 640px.
# Passing 640px slices to a 512px-trained model causes internal downscaling
# which makes objects appear smaller than what the model was trained on.
SAHI_CONFIG = {
    "slice_height": 512,
    "slice_width": 512,
    "overlap_height_ratio": 0.25,
    "overlap_width_ratio": 0.25,
    "perform_standard_pred": True,   # Also run full-frame prediction
    "postprocess_type": "NMS",       # Non-Maximum Suppression
    "postprocess_match_threshold": 0.5,
    "postprocess_class_agnostic": False,
}

# --- General inference ---
INFERENCE_CONFIG = {
    "conf_threshold": 0.30,         # Lowered from 0.4 → better recall (catch more animals)
    "iou_threshold": 0.45,          # Slightly tighter NMS (reduce duplicate boxes)
    "sahi_interval_seconds": 5,     # Run SAHI scan every N seconds
    "max_det": 50,                  # Maximum detections per frame
}

# visualization
# Class-specific colors for bounding box drawing (BGR format for OpenCV)
CLASS_COLORS = {
    "cow":       (0, 255, 0),       # Green
    "buffalo":   (255, 128, 0),     # Orange
    "goat":      (0, 255, 255),     # Yellow
    "dog":       (255, 0, 0),       # Blue
    "wild_boar": (0, 0, 255),       # Red
    "monkey":    (255, 0, 255),     # Magenta
    "nilgai":    (128, 0, 255),     # Purple
    "elephant":  (0, 128, 255),     # Light brown/orange (BGR)
    "deer":      (102, 51, 0),      # Dark brown (BGR)
    "bird":      (255, 255, 0),     # Cyan (BGR)
}
